/**
 * Student binding service
 * Connects a LINE user's diet-log app to a nutritionist's student record
 * via an invite code generated by the nutritionist platform.
 */
import { supabase } from './supabase'

const STORAGE_KEY_STUDENT_ID = 'bebetter-student-id'
const STORAGE_KEY_STUDENT_NAME = 'bebetter-student-name'
const STORAGE_KEY_LINE_USER_ID = 'bebetter-line-user-id'

// ── Getters ──────────────────────────────────────────────────────

export function getBoundStudentId(): string | null {
  return localStorage.getItem(STORAGE_KEY_STUDENT_ID)
}

export function getBoundStudentName(): string | null {
  return localStorage.getItem(STORAGE_KEY_STUDENT_NAME)
}

export function isBound(): boolean {
  return !!localStorage.getItem(STORAGE_KEY_STUDENT_ID)
}

// ── Bind via invite code ──────────────────────────────────────────

/**
 * Bind a LINE account to a student record using the invite code.
 * Calls the `bind_student` Supabase RPC (security definer, safe for anon).
 *
 * @param inviteCode - 8-char code given by the nutritionist
 * @param lineUserId - LINE userId from LIFF context (or a device UUID fallback)
 */
export async function bindStudentByInviteCode(
  inviteCode: string,
  lineUserId: string,
): Promise<{ success: boolean; studentName?: string; error?: string }> {
  if (!supabase) {
    return { success: false, error: 'Supabase 未設定' }
  }

  const { data, error } = await supabase.rpc('bind_student', {
    p_invite_code: inviteCode.trim().toUpperCase(),
    p_line_user_id: lineUserId,
  })

  if (error) {
    return { success: false, error: error.message }
  }

  const result = data as { success: boolean; student_id?: string; student_name?: string; error?: string }

  if (!result.success || !result.student_id) {
    return { success: false, error: result.error ?? '綁定失敗' }
  }

  // Persist binding locally
  localStorage.setItem(STORAGE_KEY_STUDENT_ID, result.student_id)
  localStorage.setItem(STORAGE_KEY_STUDENT_NAME, result.student_name ?? '')
  localStorage.setItem(STORAGE_KEY_LINE_USER_ID, lineUserId)

  return { success: true, studentName: result.student_name }
}

// ── Device UUID fallback (when LIFF not available) ───────────────

/**
 * Returns a stable device identifier stored in localStorage.
 * Used as LINE userId fallback when LIFF is not initialized.
 */
export function getDeviceId(): string {
  const key = 'bebetter-device-id'
  let id = localStorage.getItem(key)
  if (!id) {
    id = 'device-' + crypto.randomUUID()
    localStorage.setItem(key, id)
  }
  return id
}

// ── Unbind (for testing) ──────────────────────────────────────────

export function unbind(): void {
  localStorage.removeItem(STORAGE_KEY_STUDENT_ID)
  localStorage.removeItem(STORAGE_KEY_STUDENT_NAME)
  localStorage.removeItem(STORAGE_KEY_LINE_USER_ID)
}
